Newsweek feature
henatan99/NewsWeek-page-bootstrap-clone pull request #2
Opened 2020-10-22 02:30 UTC by henatan99

Pull request for newsweek page bootstrap clone project , Micorverse.

2020-10-22 07:11 UTC, arslanbisharat requested changes
### Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

                                      ### Project Specific 

- [x]  Please make your PR descriptive. Please add more details to it. Please refer to [link ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642) from the pathway to learn more. 

- [x] Your CSS has too many font-size declarations (12), abstraction needed.

- [ ] ![bootstrap_classes_requirement](https://user-images.githubusercontent.com/58504655/96834751-fd594e80-145b-11eb-8587-3796b46c0732.png)

- [x]  Please use dry CSS wherever needed. I have given some hints through inline-comments below. Please work on it. 

- [ ]  In Bootstrap projects make sure to less use the styles.css file for styles that could be done using Bootstrap classes since that's the main goal of the exercise. Things like font-weight, flex justifications, display, etc could be implemented completely with Bootstrap classes. [Please refer to the main page of bootstrap to learn more about bootstrap. ](https://getbootstrap.com/docs/4.5/getting-started/introduction/). I have given some hints through inline-comments below. Please work on it. 

                                               ### Large Screen

- [x] In the navbar doesn't look like the original one. Please have a look below for suggestions. 

**Clone**

![chrome-capture (7)](https://user-images.githubusercontent.com/58504655/96835535-24fce680-145d-11eb-959d-07cc2b04f81b.jpg)

- [x] There should no white space in this section.

**clone**

![chrome-capture (8)](https://user-images.githubusercontent.com/58504655/96835714-642b3780-145d-11eb-8662-fab84a5e6966.jpg)

- [x] This section doesn't look like the original one. 

**clone**

![chrome-capture (9)](https://user-images.githubusercontent.com/58504655/96835852-9177e580-145d-11eb-9e9a-fabbe431d416.jpg)

- [x] There should less space. 

**clone**

![chrome-capture (10)](https://user-images.githubusercontent.com/58504655/96836086-e7e52400-145d-11eb-984f-8bd2017ad4da.jpg)

- [x] There should total of 8 items in **EDITOR'S PICK** but you have only 7. The heading of EDITOR'S PICK doesn't look like the original one. 

- [x] You have extra space in all of these sections please remove that. 

![chrome-capture (11)](https://user-images.githubusercontent.com/58504655/96836391-588c4080-145e-11eb-990c-493b15942739.jpg)

- [ ] Subscribe section should have more width than the newsletter section. n newsletter there should space between email input and signup button. 
![chrome-capture (12)](https://user-images.githubusercontent.com/58504655/96836526-896c7580-145e-11eb-974c-73405de0158b.jpg)

- [ ] ![chrome-capture (13)](https://user-images.githubusercontent.com/58504655/96836763-dcdec380-145e-11eb-8a3c-a6b86e49cd75.jpg)

- [ ] Please male Edition bold, and add proper spacing and | after each item. 

**clone**

![chrome-capture (14)](https://user-images.githubusercontent.com/58504655/96836874-05ff5400-145f-11eb-8d1d-d78ee48c8ed2.jpg)


                                             ### MEDIUM SCREEN

- [ ] Please male Edition bold, and add proper spacing and | after each item. 

**clone**

![chrome-capture (14)](https://user-images.githubusercontent.com/58504655/96836874-05ff5400-145f-11eb-8d1d-d78ee48c8ed2.jpg)

                                         ###SMALL SCREEN

- [x] On the small screen, starting from the center of the page, the content is neither properly aligned nor has proper spacing. There is an overlapping of text. Please fix that. 



**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +        </footer>
- [x] Please move footer section outside main section

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/top-story/nancy-pelosi.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/trump.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/greece-turkey-military-dispute-mediterranean.jpg"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/judge-amy-coney-barrett.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/russia-ryabkov-nuclear-weapons-talks.jpg"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/bruce-abramson-jeff-ballabon.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/david-p-goldman.png" alt="" style="padding: 0;">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/harry-j-kazianis.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/jennifer-weiss-wolf.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/mike-davis.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/richards-axe-briggs.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/robert-reich.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/opinion/shoshana-bryen.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/holy-angel-university.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/americas-best-banks-2021.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/worlds-best-specialized-hospitals-2021.png"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/best-online-shops-2021.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/americas-best-physical-rehabilitation-centers-2020.png"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/featured-section/brandspark.png" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/my-turn/doctors-black-doctors-black-women.jpg" alt=""
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/my-turn/chef-cooking-tiktok-pandemic-coronavirus.png" alt=""
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/my-turn/love-romance-italy-romeo-juliet-pandemic.jpg" alt=""
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                    <img src="assets/images/culture-and-travel/singapore-airlines.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                    <img src="assets/images/culture-and-travel/100-best-rock-albums-all-time-according-critics.png"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                    <img src="assets/images/culture-and-travel/cul-map-wes-anderson-white-cyclon-banner.jpg"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/downtown-broadway-tennessee-coronavirus-august-2020.jpg"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/houston-ballot-drop-off.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/mages/more-stories/lindsey-graham.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/protest-chicago.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/elderly-mask.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/masks-coronavirus-covid-getty-stock.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/china-xi-jinping.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/protest-chicago.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/meghan-markle-admiralty-house-sydney-australia.jpg"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/vladimir-putin.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/former-secretary-state-hillary-clinton.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                            <img src="assets/images/more-stories/us-president-donald-trump.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/rankings-and-sponored/americas-best-addiction-treatment-centers-2020.png"
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                    alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/rankings-and-sponored/gravely-pc.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/rankings-and-sponored/image-3-this-startup-making.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 07:11 UTC, arslanbisharat commented on index.html
> +                                <img src="assets/images/rankings-and-sponored/savannah-college-art-design.jpg" alt="">
- [ ] Please use text for the **alt** attribute.

2020-10-22 09:08 UTC, henatan99 commented on index.html
> +        </footer>
footer section out of main section

2020-10-23 06:33 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] On the large screen, the webpage has white space around the borders. Please work on it 

- [ ]  In the navbar doesn't look like the original one. Please have a look below for suggestions.
![chrome-capture (25)](https://user-images.githubusercontent.com/58504655/96963693-833fcd00-1522-11eb-90b1-788f56e75731.jpg)

- [ ] Please remove white space from here by adding more items
![img](https://user-images.githubusercontent.com/58504655/96835714-642b3780-145d-11eb-8662-fab84a5e6966.jpg)

- [ ]  There should total of 8 items in IN THE MAGAZINE but you have only 7.

- [ ] Newsletter has more image height than the subscribe section. 

![chrome-capture (26)](https://user-images.githubusercontent.com/58504655/96963918-f47f8000-1522-11eb-859c-e4519ecf6f5e.jpg)

- [ ] On tablet mode text of the items present in the center is present vertically. Please work on it. 

![chrome-capture (28)](https://user-images.githubusercontent.com/58504655/96964138-5cce6180-1523-11eb-98e6-195370938806.jpg)


- [ ] On small screen image should be in the center 
![chrome-capture (27)](https://user-images.githubusercontent.com/58504655/96964022-242e8800-1523-11eb-9e30-60918254ae7e.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-23 06:33 UTC, arslanbisharat commented on README.md
> +# HTML form page
remove this

2020-10-23 08:15 UTC, arslanbisharat requested changes
# Requested Changes

- [ ] Please make changes asked in previous reviews. You have not made a single commit after your second review. 
In case of any question please reach me out on slack @arslanbisharat

2020-10-23 15:57 UTC, arslanbisharat approved these changes
#  Approved

Thank you for making those changes requested by previous TSEs.
You can merge and move forward with your curriculum.

Regards,
Arslanbisharat

2020-10-23 15:57 UTC, merged